Sub Main

    do while cmd<1000
        xsh.Screen.Send("./prog_rtsp")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("1")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("1")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("1")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("7")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Session.Sleep(3000)
        xsh.Screen.Send("q")
        xsh.Screen.Send(VbCr)

        xsh.Screen.Send("./prog_rtsp")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("1")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("1")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("1")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("7")
        xsh.Screen.Send(VbCr)
        xsh.Screen.Send("0")
        xsh.Screen.Send(VbCr)
        xsh.Session.Sleep(3000)
        xsh.Screen.Send("q")
        xsh.Screen.Send(VbCr)

        cmd = cmd+1
    loop

End Sub
